# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in plate_finding.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rubocop", "~> 1.7"

gem 'plate_finding', path: '/Users/utkum/Desktop/ruby_on_rails_bootcamp/week3/w3-homework-Vortlan/plate_finding'
